services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: apms_admin
      POSTGRES_PASSWORD: r391qcm_!a#L1
      POSTGRES_DB: apms
    volumes:
      - ./models.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build:
      context: ..
      dockerfile: apms-task-tracker/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ../apms-task-tracker-frontend
    depends_on:
      - backend
    ports:
      - "8081:80"

volumes:
  postgres_data:
